### ISSUE TITLE
Required feature missing

### ISSUE THREAD

**Issue by codepathreview** [Valionka/flickster#1]
@Valionka from your code, it seems you haven't implemented [ViewHolder](http://guides.codepath.com/android/Using-an-ArrayAdapter-with-ListView#improving-performance-with-the-viewholder-pattern) pattern, even though you have checked it to be complete in README. It is a required feature.

It is important you complete all required features. Please implement the ViewHolder pattern and resubmit.

**Comment by Valionka** [comment]
thanks for pointing it out, will take care of it and resubmit

**Comment by Valionka** [comment]
done
